# Generated by Django 2.2.1 on 2020-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="upload", name="image",),
        migrations.AddField(
            model_name="upload",
            name="file",
            field=models.FileField(null=True, upload_to="files/"),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
